export type Choice = { text: string; explanation: string };
export type Exercise = {
  id: string; moduleId: string; prompt: string; kind: 'choice' | 'number';
  choices?: Choice[]; correct?: number; expected?: number; tolerance?: number; unit?: string;
  explanation: string; reading: string; imageId?: string;
};
const choice = (id: string, moduleId: string, section: number, prompt: string, answers: [string, string][], correct: number): Exercise => ({
  id, moduleId, prompt, kind: 'choice', choices: answers.map(([text, explanation]) => ({ text, explanation })), correct,
  explanation: answers[correct][1], reading: `/wiki/${moduleId}#${moduleId}-professional-${section}`,
});
const numeric = (id: string, moduleId: string, section: number, prompt: string, expected: number, unit: string, explanation: string, tolerance = 0.01): Exercise => ({ id, moduleId, prompt, kind: 'number', expected, unit, explanation, tolerance, reading: `/wiki/${moduleId}#${moduleId}-professional-${section}` });

const baseExercises: Exercise[] = [
  choice('botanika-vadnuti', 'botanika', 3, 'Rostlina vadne a bal je nasycen vodou. Který krok nejlépe rozliší příčinu?', [['Přidat další vodu.', 'Nasycený bal již nemusí mít dost kyslíku. Další voda příčinu neověřuje.'], ['Zkontrolovat kořeny, krček, odtok a vlhkost okolní půdy.', 'Vadnutí může být následkem nefunkčních kořenů; porovnejte bal i jeho okolí.'], ['Přidat dusík.', 'Hnojivo nenahrazuje funkční příjem vody a může zvýšit zasolení.']], 1),
  choice('botanika-floem', 'botanika', 5, 'Který popis floému je správný?', [['Vede cukry od zdroje do míst spotřeby či zásob.', 'Směr určuje vztah zdroj–spotřebič, který se během sezony mění.'], ['Vždy vede pouze směrem dolů.', 'Kořeny mohou být zdrojem uložených zásob; směr není univerzální.'], ['Vede jen minerály z půdy.', 'Hlavní transport vody a minerálů z kořenů zajišťuje xylém.']], 0),
  choice('botanika-stin', 'botanika', 4, 'Proč nelze nedostatek světla dlouhodobě vyřešit vyšší dávkou hnojiva?', [['Vyšší přísun dusíku vždy kompenzuje nižší ozáření.', 'Dusík může podpořit růst jen v mezích ostatních podmínek; uhlíkovou bilanci světla nenahradí.'], ['Stín omezuje pouze barvu listů, nikoli tvorbu asimilátů.', 'Osvětlení ovlivňuje fotosyntézu a dostupnou energii pro růst celé rostliny.'], ['Minerální živiny nenahrazují energii potřebnou pro fotosyntézu.', 'Pod limitujícím osvětlením samotné zvýšení živin neodstraní hlavní omezení.']], 2),
  choice('rostliny-identita', 'rostliny', 6, 'Dodávka má pouze označení „javor“. Co chybí pro kontrolu navrženého sortimentu?', [['Stačí výška sazenice a obchodní velikost.', 'Velikost sadby neidentifikuje taxon; stejně vysoké rostliny mohou mít rozdílné nároky.'], ['Druh, případně kultivar a vazba na specifikaci.', 'Přesná identita umožňuje porovnat nároky i budoucí velikost.'], ['Nic, rod vždy určuje stejné nároky.', 'Uvnitř rodu se nároky a rozměry významně liší.']], 1),
  choice('rostliny-list', 'rostliny', 2, 'Na snímku jsou pupeny proti sobě. Co je doložený závěr?', [['Jde určitě o javor mléč.', 'Vstřícné pupeny má více taxonů; rod ani druh tím není prokázán.'], ['Pupeny jsou vstřícné; pro určení doplním další znaky.', 'Popis pozorování je jistější než neodůvodněná identifikace.'], ['Vstřícné postavení spolehlivě určuje i kultivar.', 'Kultivar nelze potvrdit z jediného znaku společného více rodům.']], 1),
  choice('rostliny-kultivar', 'rostliny', 1, 'Zachová výsev semen z kultivaru vždy jeho vlastnosti?', [['Ano, pokud byla semena sklizena z jediného jedince.', 'Jediná matečná rostlina nezaručuje genetickou shodu generativního potomstva.'], ['Ano, pokud jsou semenáče v prvním roce vzhledově stejné.', 'Podobnost mladých rostlin nevylučuje pozdější rozdíly v růstu, kvetení a dalších znacích.'], ['Ne; pro zachování vlastností se často volí vegetativní množení.', 'Pohlavní rozmnožování vytváří variabilitu. Existují zvláštní případy, které vyžadují druhové znalosti.']], 2),
  choice('puda-vzorek', 'puda', 5, 'Na pozemku je navážka a původní ornice. Jak je vzorkovat?', [['Smíchat vše do jedné nádoby.', 'Směsný vzorek by zakryl rozdíly obou zón.'], ['Odebrat a označit zóny samostatně.', 'Odlišné půdní jednotky vyžadují samostatnou interpretaci.'], ['Vzít jen nejtmavší zeminu.', 'Výběr podle vzhledu bez plánu není reprezentativní.']], 1),
  choice('puda-fe', 'puda', 3, 'Co může vysvětlit chlorózu mladých listů v zásadité půdě?', [['Železo může být chemicky špatně dostupné.', 'Přítomnost prvku v půdě není totožná s dostupností kořenům; nutno ověřit i jiné příčiny.'], ['V půdě nikdy není žádné železo.', 'Bez rozboru to nelze tvrdit.'], ['Vždy pouze napadení mšicemi.', 'Příznak není specifický pro jedinou příčinu.']], 0),
  numeric('puda-objem', 'puda', 1, 'Model: vrstva půdy 0,15 m na ploše 40 m². Jaký je její geometrický objem bez ztrát a slehnutí?', 6, 'm³', 'V = plocha × mocnost = 40 × 0,15 = 6 m³. Objednávka navíc řeší sypný stav a slehnutí.'),
  choice('stanoviste-stin', 'stanoviste', 1, 'Proč může být pod korunou zároveň stín i sucho?', [['Stín snižuje výpar natolik, že kontrola vláhy není potřeba.', 'Nižší výpar neodstraňuje konkurenci kořenů ani srážkový stín.'], ['Koruna zachytává srážky a kořeny konkurují o vodu.', 'Světlo a vodní dostupnost posuzujte odděleně.'], ['Mokré listí po dešti dokládá dostatečné provlhčení kořenů.', 'Povrchová vlhkost listí nevypovídá o vodě v kořenové zóně.']], 1),
  choice('stanoviste-tolerance', 'stanoviste', 6, 'Rostlina na místě přežívá, ale nekvete a vyžaduje trvalé zásahy. Jak to interpretovat?', [['Tolerance není totéž co vhodnost pro zadanou funkci.', 'Pouhé přežití neprokazuje přijatelný výkon ani udržitelné náklady péče.'], ['Stanoviště je jistě optimální.', 'Pozorovaný výkon tomu neodpovídá.'], ['Musí jít vždy o chybný botanický název.', 'Identitu je vhodné ověřit, ale příčinu nelze takto určit.']], 0),
  numeric('stanoviste-dest', 'stanoviste', 3, 'Na nepropustnou plochu 80 m² spadlo 12 mm srážek. Kolik litrů to představuje před odečtením ztrát?', 960, 'l', '1 mm × 1 m² = 1 l; 80 × 12 = 960 l. Skutečný zachycený objem bude záviset na ztrátách.'),
  choice('mnozeni-klon', 'mnozeni', 1, 'Potřebujete zachovat vlastnosti zdravé matečné rostliny. Co posoudit nejdřív?', [['Pouze počet semen.', 'Semenáče nemusí zachovat vlastnosti kultivaru.'], ['Vhodný vegetativní způsob, pravost a zdravotní stav matečnice.', 'Zvolená metoda musí odpovídat druhu; klonování může přenášet i patogeny.'], ['Zda mají všechny řízky shodnou délku bez ohledu na druh.', 'Geometrická shoda nemá přednost před volbou vhodného materiálu a metodou pro daný taxon.']], 1),
  choice('mnozeni-otuzovani', 'mnozeni', 6, 'Proč po zakořenění neotevřít množárnu náhle na plné slunce a suchý vzduch?', [['Aklimatizace na větší výpar a ozáření musí být postupná.', 'Kořenový systém a listy se musí přizpůsobit novému prostředí.'], ['Protože každá zakořeněná rostlina má už plně funkční regulaci výparu.', 'Zakořenění samo nepotvrzuje připravenost na náhlou změnu vlhkosti a ozáření.'], ['Protože vyšší dávka hnojiva umožní vynechat otužování.', 'Minerální výživa nenahrazuje postupnou aklimatizaci.']], 0),
  numeric('mnozeni-vyteznost', 'mnozeni', 8, 'Potřebujete 90 prodejných rostlin při zadané výtěžnosti 75 %. Kolik řízků minimálně založíte?', 120, 'ks', '90 ÷ 0,75 = 120. Výtěžnost musí zahrnout všechny relevantní ztráty, jinak výsledek podhodnotí dávku.', 0),
  choice('realizace-krcek', 'realizace', 4, 'Bod nasazení hlavních kořenů je v balu zasypán. Podle čeho určíte hloubku výsadby stromu?', [['Podle horní hrany květináče bez kontroly.', 'Pěstební nádoba může skrývat příliš hluboké zasypání.'], ['Čím hlouběji, tím lépe kotví.', 'Hluboká výsadba může zhoršit podmínky krčku a kořenů.'], ['Podle nalezeného kořenového krčku a nasazení kořenů.', 'Před stanovením úrovně je nutné zjistit skutečnou polohu kořenového systému.']], 2),
  choice('realizace-prejimka', 'realizace', 3, 'Na části dodávky chybí etikety. Jak postupovat?', [['Vysadit je náhodně.', 'Nejasná identita může porušit projekt.'], ['Oddělit, označit a vyjasnit identitu před výsadbou.', 'Přejímka má odhalit nesoulad před obtížně vratným zásahem.'], ['Přepsat etikety podle sousední rostliny.', 'Sousedství nezaručuje shodný taxon.']], 1),
  numeric('realizace-mulc', 'realizace', 5, 'Výukový rozpočet: 24 m² má dostat souvislou vrstvu mulče 0,05 m. Jaký je geometrický objem před rezervou?', 1.2, 'm³', '24 × 0,05 = 1,2 m³. Ve skutečnosti odečtěte místa u krčků a zohledněte vlastnosti materiálu.'),
  numeric('pece-n', 'pece', 4, 'Zadání: dodat 4 g N/m² na 120 m² výrobkem s 10 % N. Kolik kilogramů výrobku je výpočtově potřeba?', 4.8, 'kg', '120 × 4 = 480 g N; 480 ÷ 0,10 = 4 800 g = 4,8 kg. Nejde o doporučení dávky pro konkrétní plodinu.'),
  choice('pece-bilance', 'pece', 4, 'Rozbor další fosfor neodůvodňuje. Výrobek pokrývá dusík, ale současně dodá hodně fosforu. Co z toho plyne?', [['Stačí kontrolovat dusík.', 'Přidaný fosfor se neztratí z bilančního hodnocení.'], ['Poměr živin může být nevhodný; je třeba jiný zdroj.', 'Počítejte souběžně všechny deklarované živiny.'], ['Stačí snížit dávku výrobku a předpokládat zachování původní dávky N.', 'Snížením hmotnosti směsného hnojiva klesne i dodané množství dusíku; bilanci je nutné přepočítat.']], 1),
  choice('pece-mulc', 'pece', 3, 'Proč odhrnout trvale mokrý mulč navršený na kůře kmene?', [['Aby ochrana půdy úplně zmizela.', 'Cílem je uvolnit krček, nikoli nutně odstranit mulč z celé plochy.'], ['Protože mulč nikdy nemá smysl.', 'Vhodný mulč může půdu chránit.'], ['Krček a kůra nemají být trvale zahrnuté vlhkým materiálem.', 'Kontrola krčku patří k následné péči.']], 2),
  choice('rez-krouzek', 'rez', 2, 'Kde má skončit běžný odstraňovací řez boční větve s čitelným kroužkem?', [['Vně kroužku se zachováním ochranné zóny.', 'Řez nemá zasahovat do kmene ani zanechat dlouhý pahýl.'], ['Co nejhlouběji do kmene.', 'Tím zvětšíte poškození mateřské osy.'], ['Vždy 30 cm od kmene.', 'Pevná vzdálenost nezohledňuje anatomii spoje.']], 0),
  choice('rez-rybiz', 'rez', 6, 'Proč neřezat červený rybíz mechanicky stejně jako černý?', [['Červený rybíz potřebuje každoročně odstranit všechen krátký obrost.', 'Právě krátký obrost staršího dřeva může nést květní pupeny.'], ['Oba typy plodí pouze na koncích letošních výhonů.', 'Takové zobecnění neodpovídá rozmístění produktivního dřeva a vedlo by k chybnému řezu.'], ['Liší se rozmístění a stáří plodonosného dřeva.', 'U červeného rybízu chráníme produktivní krátký obrost na starším dřevě.']], 2),
  choice('rez-kvet', 'rez', 5, 'Zlatice má po silném únorovém řezu málo květů. Která hypotéza je vhodná k ověření?', [['Bylo odstraněno loňské dřevo s květními pupeny.', 'Zkontrolujte termín řezu, pupeny a oslunění; nehnojte automaticky.'], ['Jde vždy o nedostatek fosforu.', 'Výživa není jediným možným vysvětlením.'], ['Musí být napadena kůrovcem.', 'Pro takový závěr nejsou v zadání důkazy.']], 0),
  choice('travnik-zasah', 'travnik', 5, 'Co odlišuje aerifikaci od vertikutace?', [['Jde vždy o úplně stejný zásah.', 'Cíl i zásah do profilu se liší.'], ['Aerifikace řeší pórovitost/zhutnění, vertikutace zejména povrchovou plst.', 'Metodu vybírejte podle příčiny problému a aktuálního stavu drnu.'], ['Vertikutace dodává automaticky živiny.', 'Mechanický zásah není sám o sobě hnojení.']], 1),
  choice('travnik-smes', 'travnik', 2, 'Jak vybírat travní směs?', [['Podle funkce plochy, stanoviště a možností péče.', 'Odolnost k zátěži, světlu a dostupné vodě musí odpovídat provozu.'], ['Jen podle nejnižší ceny balení.', 'Cena nepopisuje druhové složení ani vhodnost.'], ['Vždy stejnou pro stín i sportoviště.', 'Obě situace mají odlišné požadavky.']], 0),
  numeric('travnik-osivo', 'travnik', 3, 'Etiketa zvolené směsi ve cvičení uvádí 25 g/m². Kolik kg pro 180 m² bez rezervy?', 4.5, 'kg', '25 × 180 = 4 500 g = 4,5 kg. Dávka je zadaná, ne univerzální výsevek.'),
  choice('ochrana-diagnoza', 'ochrana', 2, 'Poškození kopíruje trasu stavebního pojezdu. Co nejlépe ověří hypotézu zhutnění?', [['Okamžitě přidat fungicid.', 'Postřik neověřuje fyzikální stav půdy.'], ['Porovnat profil, kořeny a vodu na trase a mimo ni.', 'Srovnávací místo pomůže oddělit lokální vliv pojezdu od společných vlivů.'], ['Přejmenovat příznak na chorobu.', 'Název bez důkazu diagnózu neposune.']], 1),
  choice('ochrana-registr', 'ochrana', 7, 'Zahraniční článek doporučuje přípravek. Co je nutné pro použití v ČR?', [['Ověřit konkrétní české povolení a podmínky použití.', 'Zahraniční doporučení nenahrazuje aktuální české rozhodnutí a etiketu.'], ['Stačí shodná účinná látka.', 'Povolení se vztahuje ke konkrétnímu přípravku a použití.'], ['Stačí, že jej nabízí e-shop.', 'Nabídka obchodu není doklad vhodnosti konkrétní aplikace.']], 0),
  choice('ochrana-ucinek', 'ochrana', 8, 'Co patří k vyhodnocení účinku ochranného zásahu?', [['Pouze počet spotřebovaných litrů.', 'Spotřeba neprokazuje biologický účinek.'], ['Jen okamžitý vzhled listů.', 'Čas a ukazatel hodnocení musí odpovídat organismu a metodě.'], ['Předem zvolený ukazatel, srovnání a termín kontroly.', 'Bez výchozího stavu a odpovídajícího času nelze závěr spolehlivě posoudit.']], 2),
  numeric('zavlaha-objem', 'zavlaha', 3, 'Čistá potřeba je 10 mm na 60 m², zadaná účinnost 80 %. Kolik litrů musí soustava dodat?', 750, 'l', '10 × 60 ÷ 0,80 = 750 l. Čistá potřeba je 600 l, zbytek zohledňuje zadanou účinnost.'),
  numeric('zavlaha-cas', 'zavlaha', 5, 'Soustava má změřený průtok 300 l/h. Za kolik minut dodá 750 l?', 150, 'min', '750 ÷ 300 = 2,5 h; 2,5 × 60 = 150 min.'),
  choice('zavlaha-odtok', 'zavlaha', 7, 'Voda odtéká dříve, než dosáhnete cílové dávky. Co zkontrolovat?', [['Zda intenzita aplikace nepřevyšuje vsak.', 'Dávka a intenzita jsou různé veličiny; řešte půdu, zařízení a případné cykly.'], ['Pouze zvýšit průtok.', 'Vyšší intenzita může odtok zhoršit.'], ['Považovat všechnu dodanou vodu za využitou.', 'Povrchový odtok není využitelná zásoba kořenů.']], 0),
  choice('stavby-odvodneni', 'stavby', 2, 'Před návrhem spádu terasy musíte znát především:', [['Pouze místní spád jedné dlaždice.', 'Lokální spád ještě nedokládá odtok od dveří, návaznost výšek ani bezpečné vyústění.'], ['Výškové napojení, směr a bezpečné místo odvedení vody.', 'Spád musí fungovat v celém systému, ne jen na části povrchu.'], ['Pouze rozměr dlaždic.', 'Rozměr dlaždice nevysvětluje výškové vztahy.']], 1),
  choice('stavby-opora', 'stavby', 6, 'Proč nelze výšku opěrné zdi odvodit pouze od vzhledu kamene?', [['Rozhoduje i zemní tlak, voda, základ a zatížení.', 'Materiál je jen jedna část konstrukčního zadání.'], ['Dobré odvodnění samo nahrazuje posouzení zemního tlaku.', 'Odvodnění je podstatné, ale nenahrazuje návrh na zbývající zatížení.'], ['Stejná tloušťka zdi funguje pro všechny výšky při použití pevného kamene.', 'Geometrie, podloží a zatížení se mění; vlastnost kamene sama stabilitu neurčí.']], 0),
  numeric('stavby-spad', 'stavby', 2, 'Zadaný spád je 2 % na vodorovné délce 5 m. Jaký je výškový rozdíl v cm?', 10, 'cm', '5 × 0,02 = 0,10 m = 10 cm. Hodnota 2 % je zadání, nikoli univerzální projektový předpis.'),
  choice('technika-servis', 'technika', 7, 'Před uvolněním ucpané sekačky je rozhodující:', [['Pouze pustit madlo a ihned sáhnout k noži.', 'Nástroj může dobíhat; zařízení musí být bezpečně odpojené podle návodu.'], ['Odstavit energie a zajistit proti spuštění podle návodu výrobce.', 'Pohyb a akumulovaná energie musí být pod kontrolou před zásahem.'], ['Přidat otáčky.', 'Zvyšování energie závadu bezpečně neřeší.']], 1),
  choice('technika-svah', 'technika', 3, 'Který sklon je bezpečný pro konkrétní žací stroj?', [['Stejný u všech strojů.', 'Konstrukce a pokyny výrobce se liší.'], ['Libovolný, když je tráva suchá.', 'Suchost sama stabilitu nezaručuje.'], ['V mezích návodu a skutečných podmínek podkladu.', 'Omezení stroje, trakce, směr jízdy i okolí se posuzují společně.']], 2),
  numeric('technika-kapacita', 'technika', 8, 'Pro rozpočet je změřený čistý výkon 600 m²/h. Kolik hodin trvá 1 500 m² bez přesunů?', 2.5, 'h', '1 500 ÷ 600 = 2,5 h. Přesun, čištění a přestávky se do celkové zakázky připočítají zvlášť.'),
  choice('bezpecnost-volani', 'bezpecnost', 9, 'Dospělý nereaguje a místo je bezpečné. Kdy podle změnového listu ČČK 2026 volat pomoc?', [['Až po několika minutách pozorování.', 'Nereagování je důvod k okamžitému přivolání pomoci.'], ['Ihned; normální dýchání posuzovat v průběhu hovoru.', 'Aktuální český postup neodkládá volání až na dokončení kontroly dýchání.'], ['Až po návratu vedoucího.', 'Přítomnost vedoucího není podmínkou volání 155.']], 1),
  choice('bezpecnost-priorita', 'bezpecnost', 2, 'Jaké opatření má obecně přednost před pouhým přidáním OOPP?', [['Odstranění nebezpečí nebo bezpečnější způsob práce.', 'OOPP jsou poslední vrstvou; pokud lze riziko odstranit u zdroje, je to účinnější.'], ['Písemné upozornění bez změny odstranitelně nebezpečné technologie.', 'Informování nenahrazuje dostupné opatření, které nebezpečí odstraní u zdroje.'], ['Zkrácení přestávek, aby expozice skončila dříve.', 'Zrychlení může zvýšit únavu a pravděpodobnost chyby; nejde o náhradu odstranění nebezpečí.']], 0),
  choice('bezpecnost-brana', 'bezpecnost', 9, 'Co chybí nouzovému plánu uzamčeného areálu, když zná jen ulici?', [['Jen jméno správce bez kontaktu a zajištěného přístupu.', 'Samotné jméno neřeší dosažitelnost ani otevření uzamčeného vjezdu.'], ['Jen GPS bod uprostřed areálu bez dostupné příjezdové trasy.', 'Poloha je užitečná, ale uzamčený či nevhodný vjezd může pomoc stále zdržet.'], ['Konkrétní vjezd, otevření brány, poloha a navedení pomoci.', 'Přesná dostupnost pracoviště omezuje zdržení.']], 2),
  choice('navrh-zadani', 'navrh', 1, 'Které zadání je ověřitelné při předání?', [['„Ať je to hezké.“', 'Není jasné, jak shodu posoudit.'], ['Vymezená funkce plochy, výměra, materiál a kritéria převzetí.', 'Konkrétní zadání umožňuje zkontrolovat výsledek.'], ['„Použít kvalitní rostliny“ bez specifikace taxonů a přejímacích znaků.', 'Pojem kvality musí být rozveden do kontrolovatelných parametrů.']], 1),
  choice('navrh-dospele', 'navrh', 7, 'Proč v osazovacím plánu znát dospělou šířku rostlin?', [['Aby bylo možné posoudit budoucí prostor a konkurenci.', 'Prodejní velikost je jen počáteční stav.'], ['Aby se všechny rostliny daly vysadit do stejného sponu.', 'Dospělé rozměry se mezi taxony liší.'], ['Protože velikost sadby nikdy nehraje roli.', 'Velikost sadby ovlivňuje realizaci, ale nestačí pro dlouhodobý plán.']], 0),
  numeric('navrh-meritko', 'navrh', 2, 'Na plánu v měřítku 1 : 100 měří cesta 7 cm. Kolik metrů měří ve skutečnosti?', 7, 'm', '7 × 100 = 700 cm = 7 m. Měřítko musí platit pro aktuální výtisk.'),
  choice('ovocnarstvi-rajce', 'ovocnarstvi', 9, 'Máte potvrzené keříčkové rajče. Je správné automaticky odstranit všechny postranní výhony?', [['Ano, všechny kultivary se vedou stejně.', 'Růstová skupina mění postup.'], ['Ne, keříčkovým typům se běžně postranní výhony ponechávají.', 'Pravidelné vyštipování se vztahuje především k vedení tyčkových typů.'], ['Ano, stejný řez jako u tyčkových zaručí stejnou násadu plodů.', 'Shodný zásah do rozdílných růstových typů nezaručí shodný výsledek a může odstranit produktivní výhony.']], 1),
  numeric('ovocnarstvi-mrkev', 'ovocnarstvi', 9, 'Cíl 800 rostlin, klíčivost 80 %, polní uplatnění vyklíčených semen 75 %. Kolik semen nejméně potřebujete? Zaokrouhlete nahoru.', 1334, 'ks', '800 ÷ (0,8 × 0,75) = 1 333,33; nejbližší vyšší celé číslo je 1 334.', 0),
  choice('ovocnarstvi-opyleni', 'ovocnarstvi', 4, 'Co ověřit při návrhu opylovacího partnera jabloně?', [['Jen stejný termín sklizně.', 'Termín sklizně neurčuje překryv kvetení.'], ['Pouze příslušnost ke stejné podnoži.', 'Podnož neurčuje pylovou kompatibilitu odrůd v koruně.'], ['Kompatibilitu odrůd, překryv kvetení a použitelnost pylu.', 'Triploidní odrůda například nemá být jediným plánovaným poskytovatelem pylu.']], 2),
  choice('sklenik-ec', 'sklenik', 4, 'EC roztoku vzrostla. Co lze bezpečně tvrdit?', [['Změnila se vodivost související s ionty; přesné složení z EC nezjistím.', 'EC neidentifikuje jednotlivé živiny ani jejich poměr.'], ['Přibylo přesně tolik dusíku jako draslíku.', 'EC neposkytuje takové rozlišení.'], ['Rostliny mají jistě optimální výživu.', 'Vyšší EC může být i projevem nežádoucího zasolení.']], 0),
  choice('sklenik-vetrani', 'sklenik', 3, 'Proč sledovat i vlhkost a proudění, ne pouze teplotu?', [['Stejná teplota vzduchu zaručuje stejnou transpiraci.', 'Rozdíl vlhkosti a proudění může při stejné teplotě změnit výparové podmínky.'], ['Společně určují výparové podmínky a riziko kondenzace.', 'Stejná teplota při různé vlhkosti nevytváří stejný režim pro rostlinu.'], ['Průměrná denní vlhkost spolehlivě vylučuje noční kondenzaci.', 'Průměr zakrývá krátkodobé maximum vlhkosti i teplotu chladného povrchu.']], 1),
  numeric('sklenik-dli', 'sklenik', 2, 'Konstantní PPFD 200 µmol/m²/s po 10 hodin. Jaký je DLI v mol/m²/den?', 7.2, 'mol/m²/den', '200 × 10 × 3 600 ÷ 1 000 000 = 7,2. Skutečné proměnlivé světlo se integruje v čase.'),
  choice('sezona-biofix', 'sezona', 3, 'Co je biofix v použitém fenologickém modelu?', [['Libovolný den, který se hodí pracovnímu plánu.', 'Posun počátku bez opory mění interpretaci modelu.'], ['Počátek akumulace definovaný modelem, například biologickou událostí nebo pevně určeným datem.', 'Přesné pravidlo se přebírá z konkrétního modelu a nemění se podle provozního pohodlí.'], ['Teplotní práh, od něhož se odečítá denní teplota.', 'Biofix určuje začátek sledování; základní teplota je jiný parametr modelu.']], 1),
  choice('sezona-puda', 'sezona', 5, 'Kalendář říká zahájit práce, ale půda se maže a tvoří hluboké koleje. Co rozhoduje?', [['Aktuální únosnost a riziko poškození půdy.', 'Kalendář je plán; stav místa může vyžadovat odklad nebo změnu postupu.'], ['Datum bez ohledu na stav.', 'Mechanické splnění data může vytvořit dlouhodobé škody.'], ['Pouze výkon motoru plánovaného stroje.', 'Výkon nenahrazuje posouzení vlhkosti, zatížení a stop po pojezdu.']], 0),
  numeric('sezona-stupnodny', 'sezona', 3, 'Jednoduchý výukový model bez horního prahu: denní průměry 12, 8, 15 °C; základ 10 °C. Záporný denní příspěvek je nula. Jaká je suma?', 7, '°C·den', 'max(12−10,0) + max(8−10,0) + max(15−10,0) = 2+0+5 = 7. Platí jen pro zadaný model.'),
  choice('podnikani-zmena', 'podnikani', 6, 'Klient během realizace rozšíří plochu. Co musí obsahovat změnový záznam?', [['Jen novou celkovou cenu bez rozsahu a termínu.', 'Bez vymezení prací a dopadu do harmonogramu není změna jednoznačná.'], ['Nový rozsah, cenu, termín a potvrzení změny.', 'Změna má být jasně oddělena od původní objednávky.'], ['Nic, dohoda se vždy domyslí později.', 'Tím vzniká spor o obsah a cenu práce.']], 1),
  numeric('podnikani-marze', 'podnikani', 5, 'Náklad je 800 Kč. Cílová marže je 20 % z prodejní ceny bez DPH. Jaká je cena?', 1000, 'Kč', 'Cena = 800 ÷ (1−0,20) = 1 000 Kč. Přirážka 20 % k nákladu by dala 960 Kč, což není marže 20 %.'),
  numeric('podnikani-prace', 'podnikani', 4, 'Dva pracovníci pracují po 6 hodinách. Kolik člověkohodin zahrne kalkulace?', 12, 'člověkohodin', '2 × 6 = 12 člověkohodin. Doba trvání zakázky může být 6 hodin, objem práce je 12.'),
  choice('profesional-hypoteza', 'profesional', 4, 'Jaký výsledek nejvíc posiluje pracovní hypotézu?', [['Každé pozorování prohlásím za potvrzení.', 'Hypotéza musí připustit také vyvrácení.'], ['Ověřovací zásah mění jednu relevantní věc a má srovnání.', 'Tak lze lépe odlišit příčinu a současnou náhodnou změnu.'], ['Změním zároveň vodu, hnojivo i postřik.', 'Následný efekt nelze spolehlivě připsat jednotlivému zásahu.']], 1),
  choice('profesional-meze', 'profesional', 6, 'Co udělat, když dostupné údaje nerozliší dvě příčiny s opačnou nápravou?', [['Vybrat sebejistě levnější závěr bez důkazu.', 'Chybné rozhodnutí může problém zhoršit.'], ['Zamlčet nejistotu klientovi.', 'Klient potřebuje rozumět mezím doporučení.'], ['Popsat nejistotu a získat údaj, který rozhodnutí skutečně rozliší.', 'Cílené měření má větší hodnotu než další obecné tvrzení.']], 2),
  choice('profesional-zaznam', 'profesional', 5, 'Proč označit vzorek místem, datem a rostlinou?', [['Aby výsledek šel spojit s konkrétním problémem.', 'Bez návaznosti ztrácí laboratorní údaj praktickou interpretační hodnotu.'], ['Aby laboratoř mohla určit datum odběru jen ze vzhledu materiálu.', 'Datum musí být zaznamenáno; ze vzhledu jej nelze spolehlivě zpětně zjistit.'], ['Aby bylo možné bez rozlišení sloučit zdravé i poškozené zóny.', 'Sloučení rozdílných zón může zakrýt kontrast potřebný pro diagnózu.']], 0),
  { ...choice('rostliny-foto-dub', 'rostliny', 2, 'Kterému rodu odpovídá laločnatý list na referenčním snímku?', [['Tilia — lípa', 'List lípy je srdčitý a pilovitý, ne takto laločnatý.'], ['Quercus — dub', 'Oblé laloky odpovídají referenčnímu listu dubu. Samotný snímek nestačí na rozlišení všech druhů dubů.'], ['Acer — javor', 'Referenční javor má dlanitě uspořádané laloky.']], 1), imageId: 'dub-letni-list' },
  { ...choice('rostliny-foto-javor', 'rostliny', 2, 'Jak je na snímku členěný list?', [['Dlanitě laločnatý.', 'Výrazné laloky se rozbíhají od společné báze.'], ['Složený z oddělených lístků.', 'Čepel je souvislá, nejde o složený list.'], ['Peřenolaločný podél jedné hlavní osy.', 'Hlavní laloky a žilky na referenčním javoru vycházejí dlanitě od báze.']], 0), imageId: 'javor-mlec-list' },
  { ...choice('rostliny-foto-lipa', 'rostliny', 2, 'Které dva znaky můžete na snímku přímo pozorovat?', [['Klínovitou bázi a celokrajnou čepel.', 'Na referenčních listech je báze srdčitá a okraj zřetelně pilovitý.'], ['Zaoblený vrchol a souměrnou klínovitou bázi.', 'Listy mají špičatý vrchol a srdčitou, místy nesouměrnou bázi.'], ['Srdčitou bázi a pilovitý okraj listu.', 'Jde o viditelné morfologické znaky; přesné určení druhu doplní další pozorování.']], 2), imageId: 'lipa-srdcita-list' },
  { ...choice('ochrana-foto-msice', 'ochrana', 3, 'Co snímek prokazuje a co ještě ne?', [['Kolonii mšic; sám neurčuje nutnost postřiku.', 'O zásahu rozhoduje hostitel, rozsah, vývoj poškození a kontext IOR.'], ['Přítomnost kolonie automaticky dokládá překročení prahu zásahu.', 'Práh závisí na plodině, fázi vývoje, četnosti a tolerovaném poškození.'], ['Z jediného detailu lze určit procento napadených rostlin v porostu.', 'Detail nepotvrzuje četnost v porostu; ta vyžaduje reprezentativní monitoring.']], 0), imageId: 'msice-detail' },
  { ...choice('ochrana-foto-padli', 'ochrana', 1, 'Srovnání připomíná referenční snímek padlí. Co je správný další závěr?', [['Všechny bílé povlaky mají jediného původce.', 'Podobnost není jednoznačný diagnostický test.'], ['Je to pracovní hypotéza; ověřím hostitele a další znaky.', 'Zdrojově určená fotografie slouží ke srovnání, ne k automatickému potvrzení jiného případu.'], ['Fotografie dovoluje vynechat prohlídku rostliny.', 'Prohlídka a historie jsou stále potřebné.']], 1), imageId: 'padli-jablonove' },
];

const readingOverrides: Record<string, string> = {
  'pece-n': '/wiki/pece#davka-hnojiva-b-2',
  'pece-bilance': '/wiki/pece#davka-hnojiva-b-3',
  'zavlaha-objem': '/wiki/zavlaha#bilance-zavlahy-b-2',
  'zavlaha-cas': '/wiki/zavlaha#bilance-zavlahy-b-3',
  'ovocnarstvi-rajce': '/wiki/ovocnarstvi#rajce-vedeni',
  'ovocnarstvi-mrkev': '/wiki/ovocnarstvi#mrkev-vysev-b-3',
  'ovocnarstvi-opyleni': '/wiki/ovocnarstvi#jablon-podnoz-opyleni-b-2',
  'rez-rybiz': '/wiki/rez#rybiz-dva-rezimy',
  'rez-kvet': '/wiki/rez#rez-kvetoucich-keru',
  'rez-krouzek': '/wiki/rez#rez-vetevni-krouzek',
  'ochrana-registr': '/wiki/ochrana#ochrana-rozhodnuti',
  'bezpecnost-volani': '/wiki/bezpecnost#bezpecnost-aktualni-postup',
};
export const exercises: Exercise[] = baseExercises.map((exercise) => ({ ...exercise, reading: readingOverrides[exercise.id] ?? exercise.reading }));

export function parseNumericAnswer(value: string): number | null {
  if (!/^[+-]?(?:\d+(?:[.,]\d*)?|[.,]\d+|\d{1,3}(?:[ \u00a0\u202f]\d{3})+(?:[.,]\d*)?)$/.test(value.trim())) return null;
  const normalized = value.trim().replace(/[\s\u00a0]/g, '').replace(',', '.');
  if (!/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)$/.test(normalized)) return null;
  const number = Number(normalized);
  return Number.isFinite(number) ? number : null;
}
export function gradeExercise(exercise: Exercise, value: string): boolean {
  if (exercise.kind === 'choice') return /^\d+$/.test(value) && Number(value) === exercise.correct;
  const number = parseNumericAnswer(value);
  return number !== null && Math.abs(number - exercise.expected!) <= (exercise.tolerance ?? 0.01) + Number.EPSILON;
}

export type CaseStudy = { moduleId: string; prompt: string; rubric: string[] };
export const caseStudies: CaseStudy[] = [
  { moduleId: 'botanika', prompt: 'Nově přesazená rostlina vadne v mokré půdě. Navrhněte postup, který rozliší alespoň dvě příčiny.', rubric: ['Vlhkost zvlášť v balu a okolí.', 'Stav jemných kořenů, krčku a odtoku.', 'Alespoň dvě hypotézy a údaj, který je rozliší.', 'Jeden ověřovací zásah a termín kontroly.'] },
  { moduleId: 'rostliny', prompt: 'Máte pouze větev bez květu a etikety. Připravte popis pro spolehlivé určení.', rubric: ['Postavení a morfologie pupenů/listů.', 'Fotografie celku, detailu a měřítka.', 'Dvě zaměnitelné skupiny a chybějící rozlišovací znaky.', 'Jasné oddělení jistého pozorování a domněnky.'] },
  { moduleId: 'puda', prompt: 'Jedna část zahrady je navážka, druhá původní půda. Navrhněte odběrový plán.', rubric: ['Samostatné půdní jednotky.', 'Reprezentativní dílčí odběry a stejná hloubka v jednotce.', 'Označení vzorků a historie vstupů.', 'Metoda laboratoře a účel interpretace.'] },
  { moduleId: 'stanoviste', prompt: 'Vyberte podklady pro výsadbu u západní zdi pod vzrostlým stromem.', rubric: ['Denní a sezonní oslunění.', 'Kořenová konkurence a srážkový stín.', 'Půdní profil a využitelný prostor.', 'Teplotní extrémy a dostupnost péče.'] },
  { moduleId: 'mnozeni', prompt: 'Z 200 řízků jich 80 zakořenilo a 60 přežilo otužení. Co musí říci výrobní záznam?', rubric: ['40 % zakořenění a 30 % celková výtěžnost.', 'Odlišení fází ztrát.', 'Původ matečnice, hygiena a prostředí.', 'Cílený pokus pro příští dávku.'] },
  { moduleId: 'realizace', prompt: 'Při přejímce stromu objevíte spirálovité kořeny a zasypaný krček. Připravte rozhodnutí.', rubric: ['Dokumentace vady a porovnání specifikace.', 'Rozlišení napravitelné a závažné vady.', 'Určení skutečné polohy kořenů před hloubkou výsadby.', 'Pozastavení výsadby a projednání nejasného materiálu.'] },
  { moduleId: 'pece', prompt: 'Výsadba žloutne. Klient požaduje hnojivo. Co zjistíte, než určíte dávku?', rubric: ['Identita, stáří a rozložení příznaků.', 'Světlo, vlhkost, kořeny, pH a salinita.', 'Rozbor a historie vstupů.', 'Bilanční výpočet a následné hodnocení.'] },
  { moduleId: 'rez', prompt: 'Ve stejné zahradě jsou zlatice, černý rybíz a červený rybíz. Zdůvodněte, proč nestačí jeden termín a způsob řezu.', rubric: ['Květní pupeny zlatice na předchozích výhonech.', 'Obnova mladšího produktivního dřeva černého rybízu.', 'Zachování plodonosného obrostu červeného rybízu.', 'Druh, tvar, vitalita a místní vegetační průběh.'] },
  { moduleId: 'travnik', prompt: 'Trávník řídne v pochozí trase. Navrhněte rozhodnutí mezi dosetím a úpravou provozu.', rubric: ['Kořenový profil a zhutnění.', 'Světlo, voda a intenzita zátěže.', 'Příčina musí být řešena před dosetím.', 'Cíl plochy a případná změna její funkce.'] },
  { moduleId: 'ochrana', prompt: 'Listové skvrny připomínají atlas. Sepište plán před jakoukoli chemickou aplikací.', rubric: ['Hostitel, orgán a časoprostorový vzorec.', 'Alternativní biotické a abiotické příčiny.', 'Monitoring, nechemické možnosti a důvod zásahu.', 'Ověření aktuálního českého povolení případně vybraného přípravku.'] },
  { moduleId: 'zavlaha', prompt: 'Stejná sekce přelévá jeden kout a vysušuje druhý. Zdůvodněte, proč nestačí prodloužit čas.', rubric: ['Měření průtoku, tlaku a distribuce.', 'Kontrola hlavic, filtrů a netěsností.', 'Rozdílná infiltrace a hydrozóny.', 'Oprava příčiny a následné opakované měření.'] },
  { moduleId: 'stavby', prompt: 'Po dešti teče z nové terasy voda ke dveřím. Co musí obsahovat návrh opravy?', rubric: ['Zaměřené výšky a napojení.', 'Bezpečné odvedení včetně přívalové situace.', 'Stav podkladních vrstev a odvodnění.', 'Koordinace stavebních detailů a kontrolní zkouška.'] },
  { moduleId: 'technika', prompt: 'Připravte pravidla pro údržbu ucpaného stroje bez rizika náhodného spuštění.', rubric: ['Návod konkrétního stroje.', 'Odstavení zdrojů a akumulované energie.', 'Zajištění proti spuštění a kontrola zastavení.', 'Kompetence obsluhy a předání závady servisu.'] },
  { moduleId: 'bezpecnost', prompt: 'Připravte nouzový scénář pro pracovníka, který přestal reagovat v uzavřeném areálu.', rubric: ['Bezpečnost místa a kontrola reakce.', 'Okamžité volání 155 a kontrola dýchání během hovoru.', 'Dostupnost AED a postup podle operátora.', 'Otevření brány a navedení záchranářů.'] },
  { moduleId: 'navrh', prompt: 'Klient chce zahradu s minimální péčí a velkým intenzivním trávníkem. Jak vyjasníte zadání?', rubric: ['Konkrétní rozpočet hodin, vody a peněz.', 'Funkce trávníku a využití ploch.', 'Varianty odpovídající stanovišti.', 'Měřitelná kritéria a přiznané kompromisy.'] },
  { moduleId: 'ovocnarstvi', prompt: 'Sestavte kontrolní list pro nákup tří jabloní do malé zahrady.', rubric: ['Odrůda, podnož a prostor dospělého stromu.', 'Tvar, opora a místní půda.', 'Kompatibilita a překryv kvetení.', 'Přejímka identity, zdraví a kořenů.'] },
  { moduleId: 'sklenik', prompt: 'Ve skleníku se zvyšuje EC, přestože dávkovač běží stejně. Co budete měřit?', rubric: ['Vstupní voda a kalibrace senzoru.', 'Reálná dávka, výpar a odtok.', 'Srovnání roztoku, substrátu a času odběru.', 'EC nerozlišuje jednotlivé ionty; podle potřeby rozbor.'] },
  { moduleId: 'sezona', prompt: 'Naplánujte týden prací, když předpověď hlásí déšť a půda už je nasycená.', rubric: ['Biologická naléhavost a únosnost.', 'Činnosti nezávislé na vstupu do mokré půdy.', 'Podmínka zastavení a znovuzahájení.', 'Náhradní kapacita a komunikace změny.'] },
  { moduleId: 'podnikani', prompt: 'Zakázka vydělává na papíře, ale dochází peníze před splatností faktury. Vysvětlete rozdíl a navrhněte plán.', rubric: ['Zisk a cash-flow jsou odlišné.', 'Čas nákupů, mezd a inkasa.', 'Zálohy či etapové platby sjednané se zákazníkem.', 'Rezerva a kontrola úplných nákladů.'] },
  { moduleId: 'profesional', prompt: 'Vaše první diagnóza se po zásahu nepotvrdila. Jak předáte výsledek klientovi?', rubric: ['Popsat výchozí hypotézu a pozorovaný výsledek.', 'Přiznat nejistotu bez dodatečného přepisování historie.', 'Navrhnout rozlišující údaj nebo konzultaci.', 'Upravit plán a určit termín další kontroly.'] },
];
