export type AtlasImage = { id: string; titleCs: string; taxon: string; sourcePage: string; imageUrl: string; creator: string; license: string; licenseUrl: string; descriptionCs: string; diagnosticLimit: string; verifiedDate: string; changesCs: string; src: string; category: string };
export const atlasImages: AtlasImage[] = [
  {
    "id": "dub-letni-list",
    "titleCs": "Dub letní – líc listu",
    "taxon": "Quercus robur",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Quercus_robur_leaf.jpg",
    "imageUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/ad/Quercus_robur_leaf.jpg/960px-Quercus_robur_leaf.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "creator": "Dmitry Makeev",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "descriptionCs": "Laločnatý list na bílém pozadí; sken herbářového vzorku.",
    "diagnosticLimit": "Tvar jednoho listu nemusí spolehlivě odlišit příbuzné duby a křížence. Porovnejte také řapík, bázi listu, pupeny a plody.",
    "verifiedDate": "2026-09-07",
    "changesCs": "Použit zmenšený náhled poskytovaný Wikimedia Commons; obrazový obsah nebyl místně upravován.",
    "src": "/atlas/dub-letni-list.jpg",
    "category": "Poznávání rostlin"
  },
  {
    "id": "dub-letni-zaludy",
    "titleCs": "Dub letní – listy a žaludy",
    "taxon": "Quercus robur",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Quercus_robur_acorns_and_leaves.jpg",
    "imageUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/ea/Quercus_robur_acorns_and_leaves.jpg/960px-Quercus_robur_acorns_and_leaves.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "creator": "Mannivu",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "descriptionCs": "Listy s oblými laloky a nezralé žaludy na větévce.",
    "diagnosticLimit": "Použijte více znaků současně. Skvrny na listech na této fotografii nejsou v metadatech určeny jako konkrétní choroba.",
    "verifiedDate": "2026-09-07",
    "changesCs": "Použit zmenšený náhled poskytovaný Wikimedia Commons; obrazový obsah nebyl místně upravován.",
    "src": "/atlas/dub-letni-zaludy.jpg",
    "category": "Poznávání rostlin"
  },
  {
    "id": "dub-letni-pupeny",
    "titleCs": "Dub letní – pupeny na konci výhonu",
    "taxon": "Quercus robur",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Quercus-robur-buds.JPG",
    "imageUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/75/Quercus-robur-buds.JPG/960px-Quercus-robur-buds.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "creator": "Sten Porse; ořez: Siebrand",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "descriptionCs": "Detail nahloučených hnědých šupinatých pupenů na konci větévky.",
    "diagnosticLimit": "Snímek ukazuje detail pupenů; pro určení druhu doplňte znaky listů a plodů.",
    "verifiedDate": "2026-09-07",
    "changesCs": "Použit zmenšený náhled poskytovaný Wikimedia Commons; obrazový obsah nebyl místně upravován.",
    "src": "/atlas/dub-letni-pupeny.jpg",
    "category": "Poznávání rostlin"
  },
  {
    "id": "javor-mlec-list",
    "titleCs": "Javor mléč – rub listu",
    "taxon": "Acer platanoides",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:2020_year._Herbarium._Acer_platanoides._img-038.jpg",
    "imageUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1c/2020_year._Herbarium._Acer_platanoides._img-038.jpg/960px-2020_year._Herbarium._Acer_platanoides._img-038.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "creator": "Dmitry Makeev",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "descriptionCs": "Sken rubu dlanitě laločnatého listu s dlouhými špičkami laloků.",
    "diagnosticLimit": "Listy se liší věkem i kultivarem. Pro odlišení javorů porovnejte pupeny, uspořádání listů a plody; zachovejte viditelné měřítko skenu.",
    "verifiedDate": "2026-09-07",
    "changesCs": "Použit zmenšený náhled poskytovaný Wikimedia Commons; obrazový obsah nebyl místně upravován.",
    "src": "/atlas/javor-mlec-list.jpg",
    "category": "Poznávání rostlin"
  },
  {
    "id": "javor-mlec-pupeny",
    "titleCs": "Javor mléč – vstřícné pupeny",
    "taxon": "Acer platanoides",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Acer_platanoides_twig_and_buds.jpg",
    "imageUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/49/Acer_platanoides_twig_and_buds.jpg/960px-Acer_platanoides_twig_and_buds.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "creator": "Tgalos90",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "descriptionCs": "Dvojice načervenalých pupenů na protilehlých stranách větévky.",
    "diagnosticLimit": "Vstřícné postavení samo druh neurčuje. Posuzujte také tvar a barvu pupenů, listy a plody.",
    "verifiedDate": "2026-09-07",
    "changesCs": "Použit zmenšený náhled poskytovaný Wikimedia Commons; obrazový obsah nebyl místně upravován.",
    "src": "/atlas/javor-mlec-pupeny.jpg",
    "category": "Poznávání rostlin"
  },
  {
    "id": "lipa-srdcita-list",
    "titleCs": "Lípa srdčitá – líc a rub listu",
    "taxon": "Tilia cordata",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Tilia_cordata_leaf.jpg",
    "imageUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f6/Tilia_cordata_leaf.jpg/960px-Tilia_cordata_leaf.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "creator": "Gmihail at Serbian Wikipedia",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "descriptionCs": "Líc a rub srdčitého pilovitého listu vedle centimetrového měřítka.",
    "diagnosticLimit": "Pro rozlišení druhů lip doplňte ochlupení rubu listu a další znaky. Neodřezávejte měřítko při použití pro srovnání rozměrů.",
    "verifiedDate": "2026-09-07",
    "changesCs": "Použit zmenšený náhled poskytovaný Wikimedia Commons; obrazový obsah nebyl místně upravován.",
    "src": "/atlas/lipa-srdcita-list.jpg",
    "category": "Poznávání rostlin"
  },
  {
    "id": "tis-cerveny-jehlice",
    "titleCs": "Tis červený – jehlice semenáčku",
    "taxon": "Taxus baccata",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Taxus_baccata_2019-04-04_8925.jpg",
    "imageUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/bc/Taxus_baccata_2019-04-04_8925.jpg/960px-Taxus_baccata_2019-04-04_8925.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "creator": "Salicyna",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "descriptionCs": "Detail plochých jehlic mladé rostliny tisu.",
    "diagnosticLimit": "Fotografie je semenáček. Pro určení dospělé dřeviny porovnejte více větévek a další znaky; snímek není podkladem k posuzování poživatelnosti.",
    "verifiedDate": "2026-09-07",
    "changesCs": "Použit zmenšený náhled poskytovaný Wikimedia Commons; obrazový obsah nebyl místně upravován.",
    "src": "/atlas/tis-cerveny-jehlice.jpg",
    "category": "Poznávání rostlin"
  },
  {
    "id": "zerav-zapadni-vetevka",
    "titleCs": "Zerav západní – šupinovité listy",
    "taxon": "Thuja occidentalis",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Thuja_occidentalis_foliage.jpg",
    "imageUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c4/Thuja_occidentalis_foliage.jpg/960px-Thuja_occidentalis_foliage.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "creator": "Nomadluap; odvozená verze: MPF",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0/",
    "descriptionCs": "Detail zploštělých zelených větévek pokrytých drobnými, navzájem se překrývajícími šupinovitými listy.",
    "diagnosticLimit": "Plochá větévka sama neodliší všechny zeravy a cypřišky. Doplňte znaky rubu větévky a šišek; původní soubor byl na Commons přejmenován po opravě určení.",
    "verifiedDate": "2026-09-07",
    "changesCs": "Použit zmenšený náhled poskytovaný Wikimedia Commons; obrazový obsah nebyl místně upravován.",
    "src": "/atlas/zerav-zapadni-vetevka.jpg",
    "category": "Poznávání rostlin"
  },
  {
    "id": "msice-detail",
    "titleCs": "Mšice na růži – detail kolonie",
    "taxon": "Aphidoidea; hostitel Rosa sp.",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Aphids_on_a_Rosebud.jpg",
    "imageUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/be/Aphids_on_a_Rosebud.jpg/960px-Aphids_on_a_Rosebud.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "creator": "merve.obekci",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/",
    "descriptionCs": "Detail růžových až oranžových mšic na mladé části růže.",
    "diagnosticLimit": "Zdroj neurčuje druh mšice. Barva ani hostitelská rostlina k určení druhu nestačí; samotná přítomnost neudává potřebnost zásahu.",
    "verifiedDate": "2026-09-07",
    "changesCs": "Použit zmenšený náhled poskytovaný Wikimedia Commons; obrazový obsah nebyl místně upravován.",
    "src": "/atlas/msice-detail.jpg",
    "category": "Choroby a škůdci"
  },
  {
    "id": "padli-jablonove",
    "titleCs": "Padlí jabloňové – příznaky na listech",
    "taxon": "Podosphaera leucotricha; hostitel Malus domestica",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Podosphaera_leucotricha_(Ellis_%26_Everh.)_E._S._Salmon_-UGA1236181.jpg",
    "imageUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c0/Podosphaera_leucotricha_%28Ellis_%26_Everh.%29_E._S._Salmon_-UGA1236181.jpg/960px-Podosphaera_leucotricha_%28Ellis_%26_Everh.%29_E._S._Salmon_-UGA1236181.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "creator": "Clemson University – USDA Cooperative Extension Slide Series, Bugwood.org",
    "license": "CC BY 3.0 us",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0/us/deed.en",
    "descriptionCs": "Bělavý povlak a svinuté mladé listy jabloně na odborném snímku příznaků.",
    "diagnosticLimit": "Podobnost s fotografií diagnózu nepotvrzuje. Doplňte hostitele, vývoj příznaků a prohlídku celé rostliny; dle potřeby laboratorní ověření.",
    "verifiedDate": "2026-09-07",
    "changesCs": "Použit zmenšený náhled poskytovaný Wikimedia Commons; obrazový obsah nebyl místně upravován.",
    "src": "/atlas/padli-jablonove.jpg",
    "category": "Choroby a škůdci"
  },
  {
    "id": "strupovitost-jablone-list",
    "titleCs": "Strupovitost jabloně – skvrny na listu",
    "taxon": "Venturia inaequalis",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Venturia_inaequalis_01.JPG",
    "imageUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/65/Venturia_inaequalis_01.JPG/960px-Venturia_inaequalis_01.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "creator": "AfroBrazilian",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "descriptionCs": "Nepravidelné hnědavé skvrny na listu; ve zdroji určeno jako Venturia inaequalis.",
    "diagnosticLimit": "Listové skvrny mají více příčin. Fotografie slouží ke srovnání příznaků, ne jako samostatný diagnostický test.",
    "verifiedDate": "2026-09-07",
    "changesCs": "Použit zmenšený náhled poskytovaný Wikimedia Commons; obrazový obsah nebyl místně upravován.",
    "src": "/atlas/strupovitost-jablone-list.jpg",
    "category": "Choroby a škůdci"
  },
  {
    "id": "strupovitost-jablone-pokrocila",
    "titleCs": "Strupovitost – rozsáhlejší poškození listu",
    "taxon": "Venturia inaequalis",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Venturia.inaequalis2.-.lindsey.jpg",
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/0/05/Venturia.inaequalis2.-.lindsey.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
    "creator": "James Lindsey",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "descriptionCs": "Rozsáhlé tmavé skvrny na listu; určení je ve zdroji označeno jako ověřené.",
    "diagnosticLimit": "Snímek má jen 640 × 426 px a je vhodný jako doplňkový příklad. Stejný vzhled jiného listu nepotvrzuje totožného původce.",
    "verifiedDate": "2026-09-07",
    "changesCs": "Použit zmenšený náhled poskytovaný Wikimedia Commons; obrazový obsah nebyl místně upravován.",
    "src": "/atlas/strupovitost-jablone-pokrocila.jpg",
    "category": "Choroby a škůdci"
  },
  {
    "id": "rez-obrastajici-rana",
    "titleCs": "Řez – rána obrůstající dřevem",
    "taxon": "Dřevina; druh ve zdroji neuveden",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Branch_Collar_Pruned.jpg",
    "imageUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c8/Branch_Collar_Pruned.jpg/960px-Branch_Collar_Pruned.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "creator": "Kingjw4",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "descriptionCs": "Starší řezná rána s výrazným valem nového dřeva na jejím okraji.",
    "diagnosticLimit": "Fotografie nezachycuje provedení řezu ani původní větevní límeček. Nelze ji používat jako návod k poloze řezu nebo jako důkaz úplného zahojení.",
    "verifiedDate": "2026-09-07",
    "changesCs": "Použit zmenšený náhled poskytovaný Wikimedia Commons; obrazový obsah nebyl místně upravován.",
    "src": "/atlas/rez-obrastajici-rana.jpg",
    "category": "Řez"
  }
];
