export type Competency = { id: string; title: string; requirement: string; modules: string[]; reading: { label: string; href: string }[]; exerciseIds: string[]; evidence: string; remaining: string };
// Editorial crosswalk to NSK 41-007-H, not an endorsement or claim of certification.
export const competencies: Competency[] = [
  { id: 'nsk-1', title: 'Určení a nároky okrasných taxonů', requirement: 'Rozlišit předložené rostliny a vysvětlit vhodné podmínky pěstování.', modules: ['rostliny', 'stanoviste'], reading: [{ label: 'Morfologický popis', href: '/wiki/rostliny#rostliny-professional-2' }, { label: 'Obrazový atlas', href: '/atlas' }], exerciseIds: ['rostliny-identita', 'rostliny-foto-dub', 'rostliny-foto-javor', 'rostliny-foto-lipa'], evidence: 'Popis určovacích znaků, srovnání fotografií a zdůvodnění stanoviště.', remaining: 'Atlas je referenční výběr, nikoli celý zkouškový sortiment. Živé určování a úplný soubor taxonů vyžadují další přípravu.' },
  { id: 'nsk-2', title: 'Příprava místa a výsadba', requirement: 'Zdůvodnit přípravu půdy, zacházení se sadbou, výsadbu a následné ošetření.', modules: ['realizace', 'puda'], reading: [{ label: 'Výsadba stromu', href: '/wiki/realizace#realizace-professional-4' }, { label: 'Odběr půdy', href: '/wiki/puda#puda-professional-5' }], exerciseIds: ['realizace-krcek', 'realizace-prejimka', 'realizace-mulc'], evidence: 'Přejímací protokol, zdůvodněná hloubka a objemový výpočet.', remaining: 'Praktická manipulace, vysazení a přejímka výsledku nejsou ověřeny online.' },
  { id: 'nsk-3', title: 'Volba a zdůvodnění řezu', requirement: 'Zvolit účel, termín a techniku péče o dřevinu či živý plot.', modules: ['rez'], reading: [{ label: 'Větevní kroužek', href: '/wiki/rez#rez-vetevni-krouzek' }, { label: 'Kvetoucí keře', href: '/wiki/rez#rez-kvetoucich-keru' }, { label: 'Dva režimy rybízu', href: '/wiki/rez#rybiz-dva-rezimy' }], exerciseIds: ['rez-krouzek', 'rez-kvet', 'rez-rybiz'], evidence: 'Vysvětlení ponechaného dřeva a popis tří odlehčovacích kroků.', remaining: 'Přesnost řezu, bezpečné vedení nástroje a provedení tvarovaného plotu vyžadují praktické ověření.' },
  { id: 'nsk-4', title: 'Založení a udržování trávníku', requirement: 'Popsat založení porostu, volbu mechanizace a důvody následných zásahů.', modules: ['travnik', 'technika'], reading: [{ label: 'Založení porostu', href: '/wiki/travnik#travnik-professional-3' }, { label: 'Plst a zhutnění', href: '/wiki/travnik#travnik-professional-5' }], exerciseIds: ['travnik-smes', 'travnik-osivo', 'travnik-zasah'], evidence: 'Výběr směsi, výpočet výsevku a rozlišení příčin řídnutí.', remaining: 'Online výsledek nepotvrzuje obsluhu stroje, přípravu plochy ani kvalitu výsevu či pokládky.' },
  { id: 'nsk-5', title: 'Následná údržba výsadeb', requirement: 'Vybrat péči podle stavu výsadby a vysvětlit účel jednotlivých činností.', modules: ['pece', 'sezona'], reading: [{ label: 'Monitoring a prahy', href: '/wiki/pece#pece-professional-7' }, { label: 'Závlahová bilance', href: '/wiki/zavlaha#bilance-zavlahy' }], exerciseIds: ['pece-mulc', 'sezona-puda', 'zavlaha-objem'], evidence: 'Zdůvodněný plán péče s kontrolním ukazatelem a termínem.', remaining: 'Kvalitu ruční práce a reakci skutečné výsadby je třeba doložit v praxi.' },
  { id: 'nsk-6', title: 'Volba hnojiva a přepočet dávky', requirement: 'Vysvětlit výživu, vhodnost výrobku, dávkování a bezpečné zacházení.', modules: ['puda', 'pece'], reading: [{ label: 'Výpočet hnojiva', href: '/wiki/pece#davka-hnojiva' }], exerciseIds: ['pece-n', 'pece-bilance', 'puda-fe'], evidence: 'Výpočet skutečné živiny, přidaných živin a kontrola jednotek.', remaining: 'Znalost výpočtu nepotvrzuje rovnoměrnou aplikaci ani správné posouzení konkrétního laboratorního rozboru.' },
  { id: 'nsk-7', title: 'Rozhodnutí o ochraně rostlin', requirement: 'Zdůvodnit ochranný postup, přípravu aplikace a bezpečnost práce.', modules: ['ochrana', 'bezpecnost'], reading: [{ label: 'Diagnóza a registr', href: '/wiki/ochrana#ochrana-rozhodnuti' }, { label: 'Právní minimum POR', href: '/wiki/ochrana#ochrana-professional-7' }], exerciseIds: ['ochrana-diagnoza', 'ochrana-registr', 'ochrana-ucinek'], evidence: 'Diferenciální diagnóza a dohledání platného povolení konkrétního použití.', remaining: 'Není ověřena kalibrace, skutečné míchání ani aplikace. Test nenahrazuje požadovanou odbornou způsobilost.' },
  { id: 'nsk-8', title: 'Čtení projektu a prostorových vztahů', requirement: 'Vysvětlit měřítko a značky a najít navržené prvky v dokumentaci.', modules: ['navrh', 'stavby'], reading: [{ label: 'Zaměření a měřítko', href: '/wiki/navrh#navrh-professional-2' }, { label: 'Výšky a spády', href: '/wiki/stavby#stavby-professional-2' }], exerciseIds: ['navrh-meritko', 'navrh-zadani', 'stavby-spad'], evidence: 'Výpočet skutečných rozměrů a zdůvodnění výškového napojení.', remaining: 'Samostatné čtení úplného projektu a vytyčení v terénu musí ověřit další úloha s reálnou dokumentací.' },
];
